### ISSUE TITLE
Chrome error

### ISSUE THREAD

**Issue by ItIsGreg** [HealthNerd-Solutions/fhir-creator#49]
On Chrome on Ubuntu fhir-creator.com throws following Error:
![image](https://github.com/trostalski/fhir-creator/assets/87172449/1f62d52d-2887-49f9-89c8-612a68efd564)

**Comment by trostalski** [comment]
maybe try to delete the database an reopen the page

**Comment by trostalski** [comment]
is this still occurring?

**Comment by trostalski** [comment]
@ItIsGreg can this be closed?
